name: Bug Report
description: Report a bug or issue with Solar Energy Optimizer
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this issue!

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please verify the following before submitting
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I am running the latest version of the integration
          required: true
        - label: I have checked the logs for error messages
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear description of what the bug is
      placeholder: Tell us what happened
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Tell us what you expected
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output
      render: shell
      placeholder: |
        Paste logs here (Settings → System → Logs)
        Filter for "solax_energy_optimizer"

  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant are you running?
      placeholder: e.g., 2024.1.0
    validations:
      required: true

  - type: input
    id: integration_version
    attributes:
      label: Integration Version
      description: What version of Solar Energy Optimizer are you using?
      placeholder: e.g., 1.0.0
    validations:
      required: true

  - type: dropdown
    id: dry_run
    attributes:
      label: Dry Run Mode
      description: Is dry run mode enabled or disabled?
      options:
        - Enabled (default)
        - Disabled
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your integration configuration (remove sensitive data)
      render: yaml
      placeholder: |
        Battery capacity: 10.0 kWh
        Max charge rate: 5.0 kW
        Strategy: minimize_cost
        etc.

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other information that might be helpful
      placeholder: Screenshots, device info, etc.
