name: Feature Request
description: Suggest an idea for Solar Energy Optimizer
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please verify the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: This feature would be useful for other users, not just me
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is
      placeholder: I'm frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear description of what you want to happen
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Other solutions or features you've considered
      placeholder: I also thought about...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New optimization strategy
        - Additional sensor/entity
        - Configuration option
        - Integration with another service
        - Performance improvement
        - User interface enhancement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: |
        I have a setup where...
        This feature would help me...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas on how this could be implemented
      placeholder: This could be implemented by...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Any other information or screenshots
      placeholder: Screenshots, mockups, links to similar features, etc.
